//#Version: 16.0.7715.1200

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/UserData/", ConfigurationName="UserDataSoap")]
public interface UserDataSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataG" +
        "etResourceIdFromClaimsAccount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid UserDataGetResourceIdFromClaimsAccount(string userClaimsAccount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataG" +
        "etResourceIdFromClaimsAccount", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid> UserDataGetResourceIdFromClaimsAccountAsync(string userClaimsAccount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataR" +
        "edactUserByResourceId", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataRedactUserByResourceId(System.Guid userUid, string updateName, bool redactTimesheet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataR" +
        "edactUserByResourceId", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataRedactUserByResourceIdAsync(System.Guid userUid, string updateName, bool redactTimesheet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataR" +
        "edactUserByClaimsAccount", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataRedactUserByClaimsAccount(string userClaimsAccount, string updateName, bool redactTimesheet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataR" +
        "edactUserByClaimsAccount", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataRedactUserByClaimsAccountAsync(string userClaimsAccount, string updateName, bool redactTimesheet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportTimesheetList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportTimesheetList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportTimesheetList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportTimesheetListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportTimesheetsDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportTimesheetsDetails(System.Guid userUid, System.Guid[] timesheetUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportTimesheetsDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportTimesheetsDetailsAsync(System.Guid userUid, System.Guid[] timesheetUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheets", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingTimesheets(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheets", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingTimesheetsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheetList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportReportingTimesheetList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheetList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportReportingTimesheetListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheetDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingTimesheetDetails(System.Guid userUid, System.Guid[] timesheetUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingTimesheetDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingTimesheetDetailsAsync(System.Guid userUid, System.Guid[] timesheetUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportStatusReports", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportStatusReports(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportStatusReports", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportStatusReportsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDrivers", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportDrivers(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDrivers", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportDriversAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPrioritizations", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportPrioritizations(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPrioritizations", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportPrioritizationsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAnalyses", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportAnalyses(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAnalyses", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportAnalysesAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportResource", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportResource(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportResource", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportResourceAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingResource", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingResource(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingResource", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingResourceAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAdminAudit", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportAdminAudit(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAdminAudit", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportAdminAuditAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportRules(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportRules", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportRulesAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportSecurity", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportSecurity(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportSecurity", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportSecurityAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportWorkflow", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportWorkflow(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportWorkflow", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportWorkflowAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportCustomFields", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportCustomFields(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportCustomFields", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportCustomFieldsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportLookupTables", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportLookupTables(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportLookupTables", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportLookupTablesAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportCalendars", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportCalendars(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportCalendars", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportCalendarsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDelegations", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportDelegations(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDelegations", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportDelegationsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportQueueJobs", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportQueueJobs(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportQueueJobs", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportQueueJobsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportUnsubscribedAlerts", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportUnsubscribedAlerts(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportUnsubscribedAlerts", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportUnsubscribedAlertsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportSubscribedReminders", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportSubscribedReminders(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportSubscribedReminders", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportSubscribedRemindersAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReminderEmails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReminderEmails(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReminderEmails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReminderEmailsAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftProject", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportDraftProject(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftProject", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportDraftProjectAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPubProject", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportPubProject(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPubProject", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportPubProjectAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProject", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingProject(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProject", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingProjectAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectBaseline", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingProjectBaseline(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectBaseline", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingProjectBaselineAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftProjectList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet UserDataExportDraftProjectList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftProjectList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportDraftProjectListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedProjectList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet UserDataExportPublishedProjectList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedProjectList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportPublishedProjectListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet UserDataExportReportingProjectList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportReportingProjectListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportIssuesRisksDeliverablesDocumentsByGuid", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportIssuesRisksDeliverablesDocumentsByGuid(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportIssuesRisksDeliverablesDocumentsByGuid", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportIssuesRisksDeliverablesDocumentsByGuidAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportIssuesRisksDeliverablesDocumentsByResClaims", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportIssuesRisksDeliverablesDocumentsByResClaims(string userClaimsAccount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportIssuesRisksDeliverablesDocumentsByResClaims", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportIssuesRisksDeliverablesDocumentsByResClaimsAsync(string userClaimsAccount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsHistoryList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportAssignmentsHistoryList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsHistoryList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportAssignmentsHistoryListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsHistoryDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportAssignmentsHistoryDetails(System.Guid userUid, System.Guid[] transactionUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsHistoryDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportAssignmentsHistoryDetailsAsync(System.Guid userUid, System.Guid[] transactionUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportUserProperties", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportUserProperties(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportUserProperties", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportUserPropertiesAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsSubmitted", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportAssignmentsSubmitted(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsSubmitted", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportAssignmentsSubmittedAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsSaved", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportAssignmentsSaved(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportAssignmentsSaved", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportAssignmentsSavedAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportEngagementList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportEngagementList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportEngagementList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportEngagementListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportEngagementsDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportEngagementsDetails(System.Guid userUid, System.Guid[] engagementUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportEngagementsDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportEngagementsDetailsAsync(System.Guid userUid, System.Guid[] engagementUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftResourcePlanList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportDraftResourcePlanList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftResourcePlanList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportDraftResourcePlanListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftResourcePlansDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportDraftResourcePlansDetails(System.Guid userUid, System.Guid[] projectUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportDraftResourcePlansDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportDraftResourcePlansDetailsAsync(System.Guid userUid, System.Guid[] projectUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedResourcePlanList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Guid[] UserDataExportPublishedResourcePlanList(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedResourcePlanList", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Guid[]> UserDataExportPublishedResourcePlanListAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedResourcePlansDetails", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportPublishedResourcePlansDetails(System.Guid userUid, System.Guid[] projectUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportPublishedResourcePlansDetails", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportPublishedResourcePlansDetailsAsync(System.Guid userUid, System.Guid[] projectUids);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingResourcePlans", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingResourcePlans(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingResourcePlans", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingResourcePlansAsync(System.Guid userUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectTasks", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingProjectTasks(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectTasks", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingProjectTasksAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectAssignments", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingProjectAssignments(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectAssignments", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingProjectAssignmentsAsync(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectResources", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string UserDataExportReportingProjectResources(System.Guid userUid, System.Guid projectUid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/UserData/UserDataE" +
        "xportReportingProjectResources", ReplyAction="*")]
    System.Threading.Tasks.Task<string> UserDataExportReportingProjectResourcesAsync(System.Guid userUid, System.Guid projectUid);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface UserDataSoapChannel : UserDataSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserDataSoapClient : System.ServiceModel.ClientBase<UserDataSoap>, UserDataSoap
{
    
    public UserDataSoapClient()
    {
    }
    
    public UserDataSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Guid UserDataGetResourceIdFromClaimsAccount(string userClaimsAccount)
    {
        return base.Channel.UserDataGetResourceIdFromClaimsAccount(userClaimsAccount);
    }
    
    public System.Threading.Tasks.Task<System.Guid> UserDataGetResourceIdFromClaimsAccountAsync(string userClaimsAccount)
    {
        return base.Channel.UserDataGetResourceIdFromClaimsAccountAsync(userClaimsAccount);
    }
    
    public string UserDataRedactUserByResourceId(System.Guid userUid, string updateName, bool redactTimesheet)
    {
        return base.Channel.UserDataRedactUserByResourceId(userUid, updateName, redactTimesheet);
    }
    
    public System.Threading.Tasks.Task<string> UserDataRedactUserByResourceIdAsync(System.Guid userUid, string updateName, bool redactTimesheet)
    {
        return base.Channel.UserDataRedactUserByResourceIdAsync(userUid, updateName, redactTimesheet);
    }
    
    public string UserDataRedactUserByClaimsAccount(string userClaimsAccount, string updateName, bool redactTimesheet)
    {
        return base.Channel.UserDataRedactUserByClaimsAccount(userClaimsAccount, updateName, redactTimesheet);
    }
    
    public System.Threading.Tasks.Task<string> UserDataRedactUserByClaimsAccountAsync(string userClaimsAccount, string updateName, bool redactTimesheet)
    {
        return base.Channel.UserDataRedactUserByClaimsAccountAsync(userClaimsAccount, updateName, redactTimesheet);
    }
    
    public System.Guid[] UserDataExportTimesheetList(System.Guid userUid)
    {
        return base.Channel.UserDataExportTimesheetList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportTimesheetListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportTimesheetListAsync(userUid);
    }
    
    public string UserDataExportTimesheetsDetails(System.Guid userUid, System.Guid[] timesheetUids)
    {
        return base.Channel.UserDataExportTimesheetsDetails(userUid, timesheetUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportTimesheetsDetailsAsync(System.Guid userUid, System.Guid[] timesheetUids)
    {
        return base.Channel.UserDataExportTimesheetsDetailsAsync(userUid, timesheetUids);
    }
    
    public string UserDataExportReportingTimesheets(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingTimesheets(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingTimesheetsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingTimesheetsAsync(userUid);
    }
    
    public System.Guid[] UserDataExportReportingTimesheetList(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingTimesheetList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportReportingTimesheetListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingTimesheetListAsync(userUid);
    }
    
    public string UserDataExportReportingTimesheetDetails(System.Guid userUid, System.Guid[] timesheetUids)
    {
        return base.Channel.UserDataExportReportingTimesheetDetails(userUid, timesheetUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingTimesheetDetailsAsync(System.Guid userUid, System.Guid[] timesheetUids)
    {
        return base.Channel.UserDataExportReportingTimesheetDetailsAsync(userUid, timesheetUids);
    }
    
    public string UserDataExportStatusReports(System.Guid userUid)
    {
        return base.Channel.UserDataExportStatusReports(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportStatusReportsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportStatusReportsAsync(userUid);
    }
    
    public string UserDataExportDrivers(System.Guid userUid)
    {
        return base.Channel.UserDataExportDrivers(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportDriversAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportDriversAsync(userUid);
    }
    
    public string UserDataExportPrioritizations(System.Guid userUid)
    {
        return base.Channel.UserDataExportPrioritizations(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportPrioritizationsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportPrioritizationsAsync(userUid);
    }
    
    public string UserDataExportAnalyses(System.Guid userUid)
    {
        return base.Channel.UserDataExportAnalyses(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportAnalysesAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportAnalysesAsync(userUid);
    }
    
    public string UserDataExportResource(System.Guid userUid)
    {
        return base.Channel.UserDataExportResource(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportResourceAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportResourceAsync(userUid);
    }
    
    public string UserDataExportReportingResource(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingResource(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingResourceAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingResourceAsync(userUid);
    }
    
    public string UserDataExportAdminAudit(System.Guid userUid)
    {
        return base.Channel.UserDataExportAdminAudit(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportAdminAuditAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportAdminAuditAsync(userUid);
    }
    
    public string UserDataExportRules(System.Guid userUid)
    {
        return base.Channel.UserDataExportRules(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportRulesAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportRulesAsync(userUid);
    }
    
    public string UserDataExportSecurity(System.Guid userUid)
    {
        return base.Channel.UserDataExportSecurity(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportSecurityAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportSecurityAsync(userUid);
    }
    
    public string UserDataExportWorkflow(System.Guid userUid)
    {
        return base.Channel.UserDataExportWorkflow(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportWorkflowAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportWorkflowAsync(userUid);
    }
    
    public string UserDataExportCustomFields(System.Guid userUid)
    {
        return base.Channel.UserDataExportCustomFields(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportCustomFieldsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportCustomFieldsAsync(userUid);
    }
    
    public string UserDataExportLookupTables(System.Guid userUid)
    {
        return base.Channel.UserDataExportLookupTables(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportLookupTablesAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportLookupTablesAsync(userUid);
    }
    
    public string UserDataExportCalendars(System.Guid userUid)
    {
        return base.Channel.UserDataExportCalendars(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportCalendarsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportCalendarsAsync(userUid);
    }
    
    public string UserDataExportDelegations(System.Guid userUid)
    {
        return base.Channel.UserDataExportDelegations(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportDelegationsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportDelegationsAsync(userUid);
    }
    
    public string UserDataExportQueueJobs(System.Guid userUid)
    {
        return base.Channel.UserDataExportQueueJobs(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportQueueJobsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportQueueJobsAsync(userUid);
    }
    
    public string UserDataExportUnsubscribedAlerts(System.Guid userUid)
    {
        return base.Channel.UserDataExportUnsubscribedAlerts(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportUnsubscribedAlertsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportUnsubscribedAlertsAsync(userUid);
    }
    
    public string UserDataExportSubscribedReminders(System.Guid userUid)
    {
        return base.Channel.UserDataExportSubscribedReminders(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportSubscribedRemindersAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportSubscribedRemindersAsync(userUid);
    }
    
    public string UserDataExportReminderEmails(System.Guid userUid)
    {
        return base.Channel.UserDataExportReminderEmails(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReminderEmailsAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReminderEmailsAsync(userUid);
    }
    
    public string UserDataExportDraftProject(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportDraftProject(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportDraftProjectAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportDraftProjectAsync(userUid, projectUid);
    }
    
    public string UserDataExportPubProject(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportPubProject(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportPubProjectAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportPubProjectAsync(userUid, projectUid);
    }
    
    public string UserDataExportReportingProject(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProject(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingProjectAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectAsync(userUid, projectUid);
    }
    
    public string UserDataExportReportingProjectBaseline(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectBaseline(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingProjectBaselineAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectBaselineAsync(userUid, projectUid);
    }
    
    public System.Data.DataSet UserDataExportDraftProjectList(System.Guid userUid)
    {
        return base.Channel.UserDataExportDraftProjectList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportDraftProjectListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportDraftProjectListAsync(userUid);
    }
    
    public System.Data.DataSet UserDataExportPublishedProjectList(System.Guid userUid)
    {
        return base.Channel.UserDataExportPublishedProjectList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportPublishedProjectListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportPublishedProjectListAsync(userUid);
    }
    
    public System.Data.DataSet UserDataExportReportingProjectList(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingProjectList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> UserDataExportReportingProjectListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingProjectListAsync(userUid);
    }
    
    public string UserDataExportIssuesRisksDeliverablesDocumentsByGuid(System.Guid userUid)
    {
        return base.Channel.UserDataExportIssuesRisksDeliverablesDocumentsByGuid(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportIssuesRisksDeliverablesDocumentsByGuidAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportIssuesRisksDeliverablesDocumentsByGuidAsync(userUid);
    }
    
    public string UserDataExportIssuesRisksDeliverablesDocumentsByResClaims(string userClaimsAccount)
    {
        return base.Channel.UserDataExportIssuesRisksDeliverablesDocumentsByResClaims(userClaimsAccount);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportIssuesRisksDeliverablesDocumentsByResClaimsAsync(string userClaimsAccount)
    {
        return base.Channel.UserDataExportIssuesRisksDeliverablesDocumentsByResClaimsAsync(userClaimsAccount);
    }
    
    public System.Guid[] UserDataExportAssignmentsHistoryList(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsHistoryList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportAssignmentsHistoryListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsHistoryListAsync(userUid);
    }
    
    public string UserDataExportAssignmentsHistoryDetails(System.Guid userUid, System.Guid[] transactionUids)
    {
        return base.Channel.UserDataExportAssignmentsHistoryDetails(userUid, transactionUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportAssignmentsHistoryDetailsAsync(System.Guid userUid, System.Guid[] transactionUids)
    {
        return base.Channel.UserDataExportAssignmentsHistoryDetailsAsync(userUid, transactionUids);
    }
    
    public string UserDataExportUserProperties(System.Guid userUid)
    {
        return base.Channel.UserDataExportUserProperties(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportUserPropertiesAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportUserPropertiesAsync(userUid);
    }
    
    public string UserDataExportAssignmentsSubmitted(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsSubmitted(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportAssignmentsSubmittedAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsSubmittedAsync(userUid);
    }
    
    public string UserDataExportAssignmentsSaved(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsSaved(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportAssignmentsSavedAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportAssignmentsSavedAsync(userUid);
    }
    
    public System.Guid[] UserDataExportEngagementList(System.Guid userUid)
    {
        return base.Channel.UserDataExportEngagementList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportEngagementListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportEngagementListAsync(userUid);
    }
    
    public string UserDataExportEngagementsDetails(System.Guid userUid, System.Guid[] engagementUids)
    {
        return base.Channel.UserDataExportEngagementsDetails(userUid, engagementUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportEngagementsDetailsAsync(System.Guid userUid, System.Guid[] engagementUids)
    {
        return base.Channel.UserDataExportEngagementsDetailsAsync(userUid, engagementUids);
    }
    
    public System.Guid[] UserDataExportDraftResourcePlanList(System.Guid userUid)
    {
        return base.Channel.UserDataExportDraftResourcePlanList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportDraftResourcePlanListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportDraftResourcePlanListAsync(userUid);
    }
    
    public string UserDataExportDraftResourcePlansDetails(System.Guid userUid, System.Guid[] projectUids)
    {
        return base.Channel.UserDataExportDraftResourcePlansDetails(userUid, projectUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportDraftResourcePlansDetailsAsync(System.Guid userUid, System.Guid[] projectUids)
    {
        return base.Channel.UserDataExportDraftResourcePlansDetailsAsync(userUid, projectUids);
    }
    
    public System.Guid[] UserDataExportPublishedResourcePlanList(System.Guid userUid)
    {
        return base.Channel.UserDataExportPublishedResourcePlanList(userUid);
    }
    
    public System.Threading.Tasks.Task<System.Guid[]> UserDataExportPublishedResourcePlanListAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportPublishedResourcePlanListAsync(userUid);
    }
    
    public string UserDataExportPublishedResourcePlansDetails(System.Guid userUid, System.Guid[] projectUids)
    {
        return base.Channel.UserDataExportPublishedResourcePlansDetails(userUid, projectUids);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportPublishedResourcePlansDetailsAsync(System.Guid userUid, System.Guid[] projectUids)
    {
        return base.Channel.UserDataExportPublishedResourcePlansDetailsAsync(userUid, projectUids);
    }
    
    public string UserDataExportReportingResourcePlans(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingResourcePlans(userUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingResourcePlansAsync(System.Guid userUid)
    {
        return base.Channel.UserDataExportReportingResourcePlansAsync(userUid);
    }
    
    public string UserDataExportReportingProjectTasks(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectTasks(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingProjectTasksAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectTasksAsync(userUid, projectUid);
    }
    
    public string UserDataExportReportingProjectAssignments(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectAssignments(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingProjectAssignmentsAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectAssignmentsAsync(userUid, projectUid);
    }
    
    public string UserDataExportReportingProjectResources(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectResources(userUid, projectUid);
    }
    
    public System.Threading.Tasks.Task<string> UserDataExportReportingProjectResourcesAsync(System.Guid userUid, System.Guid projectUid)
    {
        return base.Channel.UserDataExportReportingProjectResourcesAsync(userUid, projectUid);
    }
}
